sudo: false
language: php

php:
  - 7.2
  - 7.3

dist: trusty

before_script:
  - export DESIGNPATTERN_TEST_ENV="travis"
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpcs --standard=PSR2 src
  - ./vendor/bin/phpcs --standard=PSR2 examples
  - ./vendor/bin/phpcs --standard=PSR2 tests
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover tests/DesignPattern/Tests/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
